### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by phillysnow** [prismicio/prismic-vue#11]
User reported issue with NUXT branch and Vue SSR
"To reproduce this you have to build a NUXT app that fetches data in asynData method, as you did in the docs. Then just build the app as it would be for production and run node server with `--expose-gc` and `--inspect`. Then in chrome under `chrome://inspect` you should find node inspector. Go to memory tab, hit the bin to garbage collect manually and take a snapshot.
Then you want to give it some traffic. I used `autocannon` on default settings. After adding some traffic you should garbage collect again and take another snapshot. Repeat this process at least once. If the heap snapshot is getting bigger (and it is) we have a memory leak.
Screenshot with snapshots attached.
Also here is a pastebin with my asyncData function https://pastebin.com/jRQQutKU"

<img width="557" alt="Screenshot 2019-05-29 at 14 17 05" src="https://user-images.githubusercontent.com/47355806/58570317-12668980-8238-11e9-98fa-a99e5b916b76.png">

**Comment by Trzosoo** [comment]
Happy to provide any further data on this matter :)

**Comment by simonmaass** [comment]
i have the same issue... after including this repo into my project memory leaks started occuring..

**Comment by MarcMcIntosh** [comment]
Hello

This branch of the kit is now deprecated and not recommended when creating Nuxt.js & Prismic projects. The recommended set up is to use the [prismic-nuxt](https://github.com/nuxt-community/prismic-module) module, you can see our [docs for that here](https://prismic.io/docs/vuejs/getting-started/prismic-nuxt) and check out this sample [project built with the module](https://github.com/prismicio/nuxtjs-website) to get going.

Out of curiosity i did take a look at some of the code snippets provided and have found a potential source of the memory leak.

```js
let document = {} // create an object (allocating memory)
let blogPosts = {}  // create an object (allocating memory)

const getHomePage = await api.getSingle('home')
const getBlogPosts = await api.query(
  Prismic.Predicates.at('document.type', 'blog_post'),
  { pageSize: 100 },
)

document = getHomePage.data // now a reference to the object getHomePage.data 
blogPosts = getBlogPosts.results // now a reference to the object getBlogPosts.results
``` 

It would be nice to see if
```js
let document;
let blogPosts;
```
or after the queries resolve
```
const document = getHomePage.data 
const blogPosts = getBlogPosts.results
```

Make any difference

seems to make a little difference in this script.
```
function leaks() {
  let x = {};
  x = "something";
  // const x = "something"; seems to fix the issue
  return x;
}

function mem (n) {
   const used = process.memoryUsage();
   const str = Object.entries(used).map(([k, v]) => {
      return k + ": " + Math.round(v / 1024 / 1024 * 100) / 100 + " MB";
   }).join("  ");
   return (n === undefined) ? str : "RUN: " + n + "  MEM: " + str;
};

console.log("START: " + mem());

for(i = 0; i < 10000; i += 1) {
   const s = leaks();
   if(i % 1000 == 0) { console.log(mem(i)) };
}

console.log("END: " + mem());
```

**Comment by MarcMcIntosh** [comment]
I decided .to write a little script to find out
```seems to make a little difference in this script.
```
function leaks() {
  let x = {};
  x = "something";
  // const x = "something"; seems to fix the issue
  return x;
}

function mem (n) {
   const used = process.memoryUsage();
   const str = Object.entries(used).map(([k, v]) => {
      return k + ": " + Math.round(v / 1024 / 1024 * 100) / 100 + " MB";
   }).join("  ");
   return (n === undefined) ? str : "RUN: " + n + "  MEM: " + str;
};

console.log("START: " + mem());

for(i = 0; i < 10000; i += 1) {
   const s = leaks();
   if(i % 1000 == 0) { console.log(mem(i)) };
}

console.log("END: " + mem());
```
> START: rss: 16.06 MB  heapTotal: 4.02 MB  heapUsed: 2 MB  external: 0.61 MB
RUN: 0  MEM: rss: 16.76 MB  heapTotal: 4.52 MB  heapUsed: 2.35 MB  external: 0.76 MB
RUN: 1000  MEM: rss: 17.08 MB  heapTotal: 4.77 MB  heapUsed: 2.66 MB  external: 0.76 MB
RUN: 2000  MEM: rss: 17.14 MB  heapTotal: 4.77 MB  heapUsed: 2.71 MB  external: 0.76 MB
RUN: 3000  MEM: rss: 17.2 MB  heapTotal: 4.77 MB  heapUsed: 2.77 MB  external: 0.76 MB
RUN: 4000  MEM: rss: 17.26 MB  heapTotal: 4.77 MB  heapUsed: 2.83 MB  external: 0.76 MB
RUN: 5000  MEM: rss: 17.85 MB  heapTotal: 5.52 MB  heapUsed: 2.5 MB  external: 0.76 MB
RUN: 6000  MEM: rss: 17.85 MB  heapTotal: 5.52 MB  heapUsed: 2.55 MB  external: 0.76 MB
RUN: 7000  MEM: rss: 17.85 MB  heapTotal: 5.52 MB  heapUsed: 2.61 MB  external: 0.76 MB
RUN: 8000  MEM: rss: 17.85 MB  heapTotal: 5.52 MB  heapUsed: 2.67 MB  external: 0.76 MB
RUN: 9000  MEM: rss: 17.85 MB  heapTotal: 5.52 MB  heapUsed: 2.72 MB  external: 0.76 MB
END: rss: 17.85 MB  heapTotal: 5.52 MB  heapUsed: 2.78 MB  external: 0.76 MB
