### ISSUE TITLE
t.reduce() is not a function

### ISSUE THREAD

**Issue by arajay** [prismicio/prismic-vue#12]
I get the console error `t.reduce() is not a function` when trying to invoke `prismic-rich-text`. My very basic `.vue` is below. I am importing PrismicVue in my `main.ts`

```
<template>
  <div>
    <prismic-rich-text :field="content" />
  </div>
</template>

<script lang="ts">
  import { Vue } from "vue-property-decorator";
  import { Component } from "vue-property-decorator";

  @Component
  export default class Home extends Vue {
    data() {
      return {
        content: {}
      };
    }
    mounted() {
      this.$prismic.client
        .getByUID("blog", "demo-page", {})
        .then(res => {
          this.content = res.data.body[3].primary.text[0].text;
        })
        .catch(e => console.log(e));
    }
  }
</script>
```

**Comment by hypervillain** [comment]
Hey, try replacing `this.content = res.data.body[3].primary.text[0].text;` by 
`this.content = res.data.body[3].primary.text`!

RichText usually looks like an array of objects and contains much more that text!

**Comment by arajay** [comment]
This did not resolve the issue. I wonder if the data is not going through the serializer properly.

**Comment by hypervillain** [comment]
Can you log your content and paste it here please? I'm pretty sure we're not passing the right element or your content lacks some properties

**Comment by arajay** [comment]
I figured this out. In addition to selecting the correct JSON element I needed to enable the runtime compiler in my vue application.
