### ISSUE TITLE
Not found in Nuxt after installing a new npm package

### ISSUE THREAD

**Issue by leopoldkristjansson** [prismicio/prismic-vue#13]
I am using:

`git+https://github.com/prismicio/prismic-vue.git#nuxt`

for my Nuxt site (Nuxt.js v2.8.1).

If I install any new package - I have to do a:

`npm install --save git+https://github.com/prismicio/prismic-vue.git#nuxt`

again, straight afterwards. Otherwise I get 
```

 ERROR  Failed to compile with 1 errors                                                                                                                                         friendly-errors 15:08:10

This dependency was not found:                                                                                                                                                  friendly-errors 15:08:10
                                                                                                                                                                                friendly-errors 15:08:10
* prismic-vue in ./plugins/prismic-vue.js
```

**Comment by leopoldkristjansson** [comment]
Just wanted to say that the seem issue occurs in a newer Nuxt project (using Nuxt 2.4.0).

**Comment by hypervillain** [comment]
Hey,

we're slowly moving people toward this repo: https://github.com/nuxt-community/prismic-module but did not make announcement yet. Can you try replacing the dependency? Good news is: in the coming weeks/months, you will gain a lot more from the NuxtJS module
