### ISSUE TITLE
Using with private API

### ISSUE THREAD

**Issue by michealjroberts** [prismicio/prismic-vue#16]
How do we use this particular plugin with a private account? It doesn't seem to be documented?

**Comment by Duaner** [comment]
Hey @michealjroberts you can find documentation for this here. 
https://prismic.io/docs/vuejs/getting-started/integrating-with-existing-project-esm

`import Vue from 'vue';
import PrismicVue from 'prismic-vue';
import linkResolver from './link-resolver';

const accessToken = 'MC5XMDNQUFNFQUFDUUFjZm9L...v73vv73vv70f77-977-9Vi0';

Vue.use(PrismicVue, {
  endpoint: window.prismic.endpoint,
  linkResolver,
  apiOptions: { accessToken }
});`
