### ISSUE TITLE
Components Only

### ISSUE THREAD

**Issue by TomKremer** [prismicio/prismic-vue#18]
Hi,

When I try to use only the components like RichText, I get a warning with linkResolver. If I add prismic-vue dependency and init with linkResolver, the issue is gone.
So my question is, what did I do wrong or is the readme (https://github.com/prismicio/prismic-vue/blame/master/README.md#L135) missing something?

![Screenshot 2019-10-28 at 19 48 51](https://user-images.githubusercontent.com/1757397/67708583-a9d53180-f9bc-11e9-8178-7909ca294f0f.png)

I'm backing in prismic content as i18n json files and I don't need the prismic javascript and whole prismic-vue.

Thanks for helping out.
Best

**Comment by hypervillain** [comment]
Hey @TomKremer, I see what's going on here. The components have always been tested with third-party libraries that added a `prismic` property to Vue prototype. This behaviour should of course be optional.

Before we find a solution, a quick fix would be to add something like this to your app:

```javascript
Vue.prototype.prismic = {
   linkResolver: () { /* ... */},
   htmlSerializer: () { /* ... */},
}
```

I can't test things right now, let me know if this works for you in the meantime!

**Comment by TomKremer** [comment]
Many thanks for your quick reply!

I got it working with the following:
`Vue.prototype.$prismic = {
   linkResolver: function(doc) {
     if (doc.type === 'home') {
         return '/';
     }
   }
}`

thx

**Comment by hypervillain** [comment]
Happy to help! I'll get back to you to see if we make this the default behaviour or update the library. And i would love to get your opinion on that of course

**Comment by hypervillain** [comment]
Hey @TomKremer,

I added these lines to the README as a default behaviour.
Thank you again for reporting this.
