### ISSUE TITLE
Need ability to pass `exact` prop to `prismic-link`

### ISSUE THREAD

**Issue by bbusch19** [prismicio/prismic-vue#20]
I need the ability to pass `exact` prop into the `prismic-link`, and have that applied to the `router-link` component that gets rendered. Otherwise, the `router-link` always gets the active class regardless of what route you're on.

Example:
```html
<prismic-link :field="to" class="primary-link" exact>
      {{ text }}
 </prismic-link>
```

**Comment by hypervillain** [comment]
Hey @bbusch19,

thank you for reporting this use case. I'll add this to our todo, expect a change in the coming days

**Comment by hypervillain** [comment]
Hey @bbusch19,

the latest version of `prismic-vue` lets you pass any attribute to the created element, so it should work. Can you confirm on your side? Thanks!
