### ISSUE TITLE
Hanging browser with version 2.0

### ISSUE THREAD

**Issue by tomgalpin** [prismicio/prismic-vue#26]
1.  In the previous version, if I had a component that had something akin to:
`<prismic-rich-text :field="item.column_title" />`

And I misspelled "title" as "_tile_," for example.  Vue would just fail to render the component.

2.  Now, when making the same typo the browser and my terminal display an error as:
"[Vue warn]: Error in render: "TypeError: Cannot read property 'reduce' of undefined."

3.  Within this error, and/or if I refresh the browser, the browser will hang forever.  Thus I have to close the tab (which sometimes will not close), restart my local server, and then open up a new tab for my localhost.

**Comment by hypervillain** [comment]
I _think_ this should be solved now: https://github.com/prismicio/prismic-vue/blob/master/src/components/RichText.js#L26 for `@prismicio/vue@2.0.6`
