### ISSUE TITLE
Update dependency to newest version

### ISSUE THREAD

**Issue by simonmaass** [prismicio/prismic-vue#28]
prismic-javascript >2.7

**Comment by simonmaass** [comment]
@arnaudlewis 

"prismic-javascript": "^2.7.0"
"prismic-dom": "^2.2.3"

**Comment by hypervillain** [comment]
Hey @simonmaass,

I bumped both dependencies in [2.0.1](https://www.npmjs.com/package/prismic-vue/v/2.0.1)

**Comment by simonmaass** [comment]
<3 thx

**Comment by hypervillain** [comment]
🙌
