### ISSUE TITLE
Console.log in source code

### ISSUE THREAD

**Issue by LukasCornille** [prismicio/prismic-vue#30]
In prismic-vue.esm.js on line 299 there's a log statement. I don't think this is intentional?

![Annotation 2020-05-31 150138](https://user-images.githubusercontent.com/36887321/83352958-822db980-a34f-11ea-992c-c8257405aa7a.png)

**Comment by hypervillain** [comment]
No it's not 🙈 Getting rid of it on next release (soon)

**Comment by hypervillain** [comment]
Done, you can update to 2.0.4. Install `@/prismicio/vue` if you haven't done it yet, we're slowly moving all existing repositories under prismicio org.

Thanks for your patience ✌️
