### ISSUE TITLE
Example code show Vue warning "Invalid prop"

### ISSUE THREAD

**Issue by supermueller** [prismicio/prismic-vue#36]
If you follow the instructions in the readme, you get an Vue warning saying `Invalid prop: type check failed for prop "field". Expected Array, got Null`.

To fix this, avoid using `null` when init the properties; instead use empty arrays or objects:

```js
export default {
  name: 'MyComponent',
  data() {
    return {
      fields: {
        title: [],
        logo: {},
        somethingRich: []
      }
    }
  },
  …
}
```

**Comment by lihbr** [comment]
Hey @supermueller thank you for contributing, nice catch! If you're willing to make a quick PR that's more than appreciated ☺️

**Comment by KayJay89** [comment]
The documents over at https://prismic.io/docs/vuejs/getting-started/integrating-with-an-existing-project should also be updated.
