### ISSUE TITLE
Instructions for importing directly within a component

### ISSUE THREAD

**Issue by U3R1YXJ0** [prismicio/prismic-vue#47]
Rather than importing prismic-vue globally, I would like to import it only in the components that require getting and rendering prismic data in order to avoid increasing my vendor webchunk size unnecessarily. Could be a good addition to the readme?

**Comment by lihbr** [comment]
Hey @U3R1YXJ0, thanks for your suggestion! We'll consider that!

Right now you can use the kit components without using the whole plugin. That's what we're doing on the [Nuxt module](https://github.com/nuxt-community/prismic-module/blob/master/src/templates/plugins/prismic-components.js).

I guess what you could also do is creating a second Vue.js instance that you only import/use on your Prismic related pages. I would experiment that way.

**Comment by lihbr** [comment]
Technical references now document how to use components on their own 🎉 (in all fairness it's been some time since they do now)

Example: https://prismic.io/docs/technical-reference/prismicio-vue#prismicrichtext

Thank you for your contribution!
