### ISSUE TITLE
Link to a Document doesn't work :  <prismic-link> and in the rich_text 

### ISSUE THREAD

**Issue by lougea** [prismicio/prismic-vue#53]
Hello @lihbr ,

since yesterday the feature "link to a document "doesn’t work. The prismic-link works normally with an external url, but not to a  prismic document. Same problem in the richtext.

Thanks for your work!

```
  "vue": "^3.2.16",
 "@prismicio/vue": "^3.0.0-alpha.6"
```
https://we.tl/t-o4RM8joL2S

**Edit :** 

After my post i realized that the links in my menu works normally, in my pricing page (single type), but not in the my Repeatable Type pages

I cloned your repo: https: //github.com/lihbr/prismic-demo-the-last-straw/

And tried to add prismic documents links (rich_text and <prismic-link />) between two repeatable type pages (recipes), and i have the same issue.

The path is updated but not the redirection

**Edit :** 

Problem comes from vue-router (router-view), not from your side. Thanks

**Comment by lihbr** [comment]
Hey @lougea, so sorry I passed through your issue! Glad you're trying the new kit and found a fix to your issue! 💐
