### ISSUE TITLE
Improve Image component accessibility

### ISSUE THREAD

**Issue by VincentHardouin** [prismicio/prismic-vue#55]
Hello ! 

I have a problem with `alt` attribute in Image component. 

When `alt` is not provided in Prismic, API returns `null` and `alt` attribute is not set. Otherwise,  this attribute is very important for accessibility [even if empty](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML#empty_alt_attributes).  

When I look at  [the component](https://github.com/prismicio/prismic-vue/blob/master/src/components/Image.js), I see two options : 

## The first one

It consists in inverting `assign` like this  : 

```jsx
return h(
			'img',
			Object.assign(data, {
				attrs: {
					src: url,
					alt,
					copyright
					...data.attrs,
				}
			})
	);
```

This allows overriding all fields from Prismic. 

## The second one

It consists in handling `alt` field.

```jsx
return h(
			'img',
			Object.assign(data, {
				attrs: {
					src: url,
					alt: alt || '',
					copyright
					...data.attrs,
				}
			})
	);
```

I can develop whichever suits you.

**Comment by lihbr** [comment]
Hey there, awesome catch! I'll deal with that this week on the Vue 2 & Vue 3 version following the 2nd strategy you described (accessibility by default) ☺️

**Comment by lihbr** [comment]
Released as part of:
- `@prismicio/vue@2.1.2` for Vue 2
- `@prismicio/vue@3.0.0-beta.4` for Vue 3

Thanks for the heads up! Let us know if you encounter any more undesired behavior~ 🚀

**Comment by VincentHardouin** [comment]
Thanks for your speed ! 🚀
