### ISSUE TITLE
Requirement on the template compiler

### ISSUE THREAD

**Issue by CalebKester** [prismicio/prismic-vue#6]
Are there any plans on removing this dependency so we don't need to include the compiler in the build?
```[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

found in

---> <Anonymous>
       <PrismicEditButton> at /Users/jbdebiasio/dev/prismic-vue/src/components/EditButton.vue
         <Page> at src/views/Page.vue
           <App> at src/App.vue
             <Root>
```

![image](https://user-images.githubusercontent.com/1319995/48178810-42bcf980-e2e1-11e8-8907-dc18fb91e919.png)

**Comment by lihbr** [comment]
I'm really sorry to read what happened to this PR back then, this will change! 💪 In the meantime, this issue is not one anymore~
