### ISSUE TITLE
defineSliceZoneComponents jsdoc @example isn't formatted nicely

### ISSUE THREAD

**Issue by danielphilipjohnson** [prismicio/prismic-vue#61]
### Versions

- @prismicio/vue: 3.1.0

### Reproduction
Hovering over `defineSliceZoneComponents` the code isn't formatted and a little hard to read

![image](https://user-images.githubusercontent.com/61696382/189185414-4c32a74a-6e01-44ec-899b-b637ab6f3e95.png)

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
Refer to above
### What is expected?
To format nicely 
### What is actually happening?
Spacing isn't observed

## Fix 
This line will stop jsdoc from formatting the line
`@example Defining a slice components:`
A Possible solution is to move this to a @description Defining a slice components. However, the linting tool formats it the following way 👀 

![image](https://user-images.githubusercontent.com/61696382/189188075-a438a74e-6140-4cc7-b70d-77fe4fb9c7e2.png)

After the change It now appears like this:

![image](https://user-images.githubusercontent.com/61696382/189186641-2e886be9-205f-456b-9207-0923a4d4d365.png)
All nicely formatted 😄

**Comment by lihbr** [comment]
Hey Daniel,

Thanks for opening this issue and PR and sorry for the delay - as I think you know I was away these last weeks.

I'm not sure about the `@description` tag as it doesn't appear to be part of the TSDoc spec: https://tsdoc.org/pages/tags/example (or maybe I'm missing something, but it is part of the JSDoc spec indeed)

I'll follow up in the PR :)

**Comment by lihbr** [comment]
Closed in #62, #67, thanks Daniel! ❤️
