### ISSUE TITLE
PrismicEmbed with youtube url displays it on 200x113

### ISSUE THREAD

**Issue by priverop** [prismicio/prismic-vue#65]
### Versions

- @prismicio/vue: 2.2.0
- vue: 2.7.14
- node: 16.17.0
- @nuxtjs/prismic: 1.4.2

### Reproduction

```vue
<template>
  <section :data-slice-type="slice.slice_type" :data-slice-variation="slice.variation">
    <PrismicEmbed :field="slice.primary.video" />
  </section>
</template>

<script>
import { getSliceComponentProps } from '@prismicio/vue/components'

export default {
  // The array passed to `getSliceComponentProps` is purely optional.
  // Consider it as a visual hint for you when templating your slice.
  props: getSliceComponentProps(['slice', 'index', 'slices', 'context']),
}
</script>
<style lang="scss" scoped>
/* Style YouTube embed */
iframe,
.yt,
[data-oembed-provider='YouTube'] {
  width: 1004px;
}
</style>

```

The smaller video is the PrismicEmbed component. The bigger video is a custom iframe I made.
![image](https://github.com/prismicio/prismic-vue/assets/1587633/a7f7f69c-71af-409a-8597-b3d440b70460)

### Steps to reproduce

1. Create an Slice with the Embed or Url field.
2. Use the PrismicEmbed component to display the slice.

### What is expected?

That I could modify the size of the displayed video.

### What is actually happening?

The size is fixed because the iframe is being rendered with a fixed size.

### Issues on the Forum

None of these solutions work.

- https://community.prismic.io/t/primic-embed-component-in-vue/7794/3 
- https://community.prismic.io/t/video-embedding-advice/212/2

I've seen many people suggesting using Custom HTML Fields or similar, but then what's the point of this PrismicEmbed? It's not posible to avoid using fixed width and height?

Thank you!

**Comment by lihbr** [comment]
Hey @priverop, thanks for opening an issue and sorry for the delay to get back to you,

The embed displayed by the `<PrismicEmbed />` component is the oembed response from YouTube's oembed API. We don't have control over what HTML YouTube returns to us in that case, an it appears defaults are... werid.

You should be able to style it using deep css selectors, something in that fashion in Vue 2, or at least, I'd try to poke in that direction.
```css
[data-oembed-provider="YouTube"]::v-deep iframe { /* style */ }
```

Let me know!

**Comment by lihbr** [comment]
Closing as stale, happy to reopen if needed!
