### ISSUE TITLE
this.$prismic.linkResolver is undefined

### ISSUE THREAD

**Issue by wesharehoodies** [prismicio/prismic-vue#7]
`console.log(this.$prismic.linkResolver)` returns undefined in `Vue` components.

In the source code it's defined as `Vue.prototype.$prismic.linkResolver = options.linkResolver`

Why is it undefined on the $prismic prototype?

<img width="571" alt="screen shot 2018-12-28 at 11 34 13" src="https://user-images.githubusercontent.com/11220736/50512836-8ee01b00-0a94-11e9-9801-ea92d7de6aab.png">
<img width="457" alt="screen shot 2018-12-28 at 11 34 21" src="https://user-images.githubusercontent.com/11220736/50512837-8ee01b00-0a94-11e9-9b41-169140d10b6a.png">

**Comment by wesharehoodies** [comment]
I made my own linkResolver and passed it to the options in the Vue plugin. Is this the way to go?

**Comment by henrikmerlander** [comment]
Yes, you need to define your own link resolver, since it will be specific to your app. It's described in the docs: https://prismic.io/docs/vuejs/beyond-the-api/link-resolving

**Comment by wesharehoodies** [comment]
Okay, thanks @henrikmerlander
