### ISSUE TITLE
Mandatory `options` parameter in this.$prismic.client methods

### ISSUE THREAD

**Issue by kwiat1990** [prismicio/prismic-vue#9]
Hi guys,

I've created a new project in which I want to use `prismic-vue` along with a Typescript. At first TS Compiler gave me a hard time due to lack of types for `prismic`.

After some research I've discovered the fork of this repo with all the neccessary types (great job!). But there's a catch - inconsistency between types in `prismic-javascript` and those in `prismic-vue`. For example: 
```js
this.$prismic.client.getSingle('menu') // error: Expected 2-3 arguments, but got 1.
this.$prismic.client.getSingle('menu', {}) // ok

// interface
getSingle(type: string, options: QueryOptions, cb?: RequestCallback<Document>): Promise<Document>;
```
In `prismic-javascript`  `getSingle` method requires a `type` parameter (in this case a string `menu`) while all the other are optional. On the other hand `prismic-vue` requires also `options` parameter (the empty object from the example above), which at least in this case is completely redundant. Is there any particular reason to make it mandatory?

**Comment by kkshmz** [comment]
This is also apparent in React

**Comment by hypervillain** [comment]
Hey @kwiat1990 ,

to make sure I understand the situation: what's the fork you mentioned? At the moment I'm really unsure of what could be wrong as `prismic-vue` does not re-declare API methods: https://github.com/prismicio/prismic-vue/blob/master/src/index.js#L25 (see this line where we simply attach the js lib to Vue's prototype)

**Comment by lihbr** [comment]
Closing regarding this issue latest activity. Next major of this kit should provide first-class TypeScript support :tada:
